name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      ###########################################################
      # General
      ###########################################################

      - name: General Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: rasyidrizky
          filename: metrics/general.svg

          template: classic

          config_timezone: Asia/Jakarta

          base: header, activity, community, repositories, metadata

      ###########################################################
      # Languages
      ###########################################################

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      
          user: rasyidrizky
          filename: metrics/languages.svg
      
          template: classic
          base: ""
      
          plugin_languages: yes
      
          # Analyze repositories in depth
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
      
          # Display
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
      
          # Show both sections
          plugin_languages_sections: most-used,recently-used
      
          # Programming languages only
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming
      
          # Extra statistics
          plugin_languages_details: bytes-size,percentage,lines
      
          plugin_languages_colors: github
      
          # Recent activity
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 30

      ###########################################################
      # Achievements
      ###########################################################

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: rasyidrizky
          filename: metrics/achievements.svg

          template: classic

          base: ""

          plugin_achievements: yes

          plugin_achievements_display: compact

          plugin_achievements_threshold: C

          plugin_achievements_secrets: no

      ###########################################################
      # Featured repositories
      ###########################################################

      - name: Repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: rasyidrizky
          filename: metrics/repositories.svg

          template: classic

          base: ""

          plugin_repositories: yes

          plugin_repositories_featured: PAWLearn,Praktikum-STEI-K-STI-ITB-2023

          plugin_repositories_featured_order: pinned
