name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      # General
      - name: General Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rasyidrizky
          filename: metrics/general.svg
          template: classic
          config_timezone: Asia/Jakarta
          base: header, activity, community, repositories, metadata
          repositories_forks: yes

      # Languages
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rasyidrizky
          filename: metrics/languages.svg
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

      # Featured repositories
      - name: Repositories
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rasyidrizky
          filename: metrics/repositories.svg
          template: classic
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: rasyidrizky/Praktikum-STEI-K-STI-ITB-2023, dzakyatha/eventguard, rasyidrizky/PAWLearn, kifu/18223114_18223116_18223139_Tugas4_II4021, Izhrr/Nangor-Valley, 
          plugin_repositories_order: featured, pinned, starred, random

      # Commit Calendar
      - name: Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rasyidrizky
          filename: metrics/calendar.svg
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      # People
      - name: People
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: rasyidrizky
          filename: metrics/people.svg
          template: classic
          base: ""
          plugin_people: yes
          plugin_people_limit: 14
          plugin_people_size: 28
          plugin_people_types: followers, following
